name: CI Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  ubuntu-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm install
        working-directory: ui

      - run: npm run build
        working-directory: ui
        env:
          CI: ""

      - name: go install
        run: go install -ldflags "-X github.com/openziti/zrok/build.Version=${{ github.ref }} -X github.com/openziti/zrok/build.Hash=${{ github.sha }}" ./...

      - name: test
        run: go test -v ./...